const STORAGE_KEY="atlasDashboardV2";
const THEME_STORAGE_KEY="atlasDashboardTheme";
const statuses=["noua","date-validate","pregatita","in-lucru","in-revizie","blocata","finalizata","arhivata"];
const labels={"noua":"Nouă","date-validate":"Date validate","pregatita":"Pregătită","in-lucru":"În lucru","in-revizie":"În revizie","blocata":"Blocată","finalizata":"Finalizată","arhivata":"Arhivată"};
const deliverableTypes=[{type:"calcule",label:"Calcule"},{type:"svg",label:"SVG-uri"},{type:"markdown",label:"Markdown"},{type:"html",label:"HTML"},{type:"revizie",label:"Revizie"}];
const skillMap={"calcule":"numerologie-dashboard","svg":"numerologie-SVG-soarta-si-destin","markdown":"numerologie-dashboard","html":"numerologie-dashboard","revizie":"numerologie-dashboard"};
const agents=[
  {name:"The Scribe",role:"Autor de lucrări",state:"working",task:"Redactează structura unei analize individuale",work:"Analiză demonstrativă",last:"acum 2 min"},
  {name:"The Cartographer",role:"Creator de hărți SVG",state:"idle",task:"Disponibil pentru următorul grafic numerologic",work:"Nicio lucrare activă",last:"acum 18 min"},
  {name:"The Lore Keeper",role:"Custodele Vaultului",state:"working",task:"Verifică legăturile și documentația numerologică",work:"Vault / Numerologie",last:"acum 5 min"},
  {name:"The Archivist",role:"Cercetare transversală",state:"idle",task:"Așteaptă un lot de lucrări pentru comparație",work:"Nicio cercetare activă",last:"acum 1 h"}
];
const transitions={"noua":["date-validate"],"date-validate":["pregatita","blocata"],"pregatita":["in-lucru","blocata"],"in-lucru":["in-revizie","blocata"],"in-revizie":["finalizata","blocata"],"blocata":["date-validate","in-lucru"],"finalizata":["arhivata"],"arhivata":[]};
const seed={persons:[{id:"pers-demo",fullName:"Persoană Demonstrativă",birthDate:"1990-01-01"}],works:[{id:"work-demo",personId:"pers-demo",title:"Analiză demonstrativă",workType:"Analiză individuală",targetDirectory:"output/lucrari/demo",status:"in-lucru",deliverables:deliverableTypes.map((d,i)=>({...d,id:`d-${i}`,state:i<2?"done":i===2?"active":"pending"})),history:[{at:"2026-07-12T10:00:00Z",from:"pregatita",to:"in-lucru",note:"Flux demonstrativ pornit"}],updatedAt:"2026-07-12T10:00:00Z",blockers:[]}]};
let state=loadState(),selectedId=state.works[0]?.id||null;
const $=id=>document.getElementById(id);
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||structuredClone(seed)}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function personFor(work){return state.persons.find(p=>p.id===work.personId)}
function progress(work){return work.deliverables.length?Math.round(work.deliverables.filter(d=>d.state==="done").length/work.deliverables.length*100):0}
function esc(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function render(){renderSummary();renderAgents();renderFilters();renderList();renderDetail()}
function renderAgents(){const stateLabel={working:"Lucrează",idle:"Idle",blocked:"Blocat"};$("agentGrid").innerHTML=agents.map(a=>`<article class="agent-card" data-state="${a.state}"><div class="agent-card-top"><div><h3>${a.name}</h3><p class="agent-role">${a.role}</p></div><span class="agent-state"><i class="dot ${a.state}"></i>${stateLabel[a.state]}</span></div><p class="agent-task">${a.task}</p><p class="agent-meta">${a.work} · ${a.last}</p></article>`).join("")}
function renderSummary(){const active=state.works.filter(w=>["pregatita","in-lucru","in-revizie"].includes(w.status)).length;const attention=state.works.filter(w=>w.status==="blocata"||w.blockers.length).length;const done=state.works.filter(w=>w.status==="finalizata").length;$("summary").innerHTML=[[state.persons.length,"Persoane"],[active,"Lucrări active"],[attention,"Necesită atenție","attention"],[done,"Finalizate"]].map(([n,l,c])=>`<article class="metric ${c||""}"><span class="eyebrow">${l}</span><strong>${n}</strong></article>`).join("")}
function renderFilters(){if(!$("statusFilter").dataset.ready){$("statusFilter").insertAdjacentHTML("beforeend",statuses.map(s=>`<option value="${s}">${labels[s]}</option>`).join(""));$("statusFilter").dataset.ready=1}const types=[...new Set(state.works.map(w=>w.workType))];$("typeFilter").innerHTML='<option value="">Toate tipurile</option>'+types.map(t=>`<option>${esc(t)}</option>`).join("")}
function filteredWorks(){const q=$("searchInput").value.toLowerCase(),s=$("statusFilter").value,t=$("typeFilter").value;return state.works.filter(w=>{const p=personFor(w);return(!q||`${w.title} ${p?.fullName}`.toLowerCase().includes(q))&&(!s||w.status===s)&&(!t||w.workType===t)})}
function renderList(){const works=filteredWorks();$("resultCount").textContent=`${works.length} rezultate`;$("workList").innerHTML=works.length?works.map(w=>{const p=personFor(w);return `<button class="work-item ${w.id===selectedId?"active":""}" data-id="${w.id}"><div class="work-item-top"><strong>${esc(p?.fullName||"Persoană lipsă")}</strong><span class="pill ${w.status}">${labels[w.status]}</span></div><small>${esc(w.workType)} · ${progress(w)}%</small></button>`}).join(""):'<div class="empty"><p>Nicio lucrare pentru filtrele alese.</p></div>';document.querySelectorAll(".work-item").forEach(b=>b.onclick=()=>{selectedId=b.dataset.id;render()})}
function requiredMissing(work){const p=personFor(work),m=[];if(!p?.fullName)m.push("numele");if(!p?.birthDate)m.push("data nașterii");if(!work.workType)m.push("tipul lucrării");if(!work.targetDirectory)m.push("directorul țintă");return m}
function renderDetail(){const w=state.works.find(x=>x.id===selectedId);if(!w){$("detail").innerHTML='<div class="empty"><div><h2>Selectează o lucrare</h2><p>Detaliile, livrabilele și istoricul apar aici.</p></div></div>';return}const p=personFor(w),missing=requiredMissing(w),next=transitions[w.status]||[];$("detail").innerHTML=`<div class="detail-head"><div><span class="eyebrow">${esc(w.id)}</span><h2>${esc(w.title)}</h2><p class="meta">${esc(p?.fullName)} · ${esc(w.workType)}<br>${esc(w.targetDirectory)}</p></div><div class="progress-wrap"><strong>${progress(w)}% complet</strong><div class="progress-track"><div class="progress-bar" style="width:${progress(w)}%"></div></div><p class="meta">Actualizat ${new Date(w.updatedAt).toLocaleString("ro-RO")}</p></div></div>${missing.length?`<div class="warning">Lipsesc: ${missing.join(", ")}. Lucrarea nu poate deveni pregătită.</div>`:""}${w.blockers.length?`<div class="warning">Blocaje: ${w.blockers.map(esc).join(", ")}</div>`:""}<div class="detail-grid"><div><h3 class="subhead">Livrabile</h3><div class="deliverables">${w.deliverables.map(d=>`<label class="deliverable"><span>${esc(d.label)}</span><select data-deliverable="${d.id}">${["pending","active","done","blocked"].map(s=>`<option value="${s}" ${d.state===s?"selected":""}>${s}</option>`).join("")}</select></label>`).join("")}</div><div class="actions-row">${next.map(s=>`<button class="btn ${s==="blocata"?"ghost":""}" data-status="${s}">${labels[s]}</button>`).join("")}<button class="btn ghost" id="exportBtn">Exportă manifestul</button></div></div><div><h3 class="subhead">Istoric</h3><div class="timeline">${w.history.slice().reverse().map(e=>`<div class="event"><strong>${labels[e.to]||e.to}</strong><p>${esc(e.note)}</p><small>${new Date(e.at).toLocaleString("ro-RO")}</small></div>`).join("")||'<p class="meta">Fără evenimente.</p>'}</div></div></div>`;document.querySelectorAll("[data-deliverable]").forEach(s=>s.onchange=()=>{w.deliverables.find(d=>d.id===s.dataset.deliverable).state=s.value;touch(w);render()});document.querySelectorAll("[data-status]").forEach(b=>b.onclick=()=>changeStatus(w,b.dataset.status));$("exportBtn").onclick=()=>exportManifest(w)}
function touch(w){w.updatedAt=new Date().toISOString();save()}
function changeStatus(w,to){if(!(transitions[w.status]||[]).includes(to))return toast("Tranziție nepermisă");if(to==="pregatita"&&requiredMissing(w).length)return toast("Completează datele obligatorii");const from=w.status;w.status=to;w.history.push({at:new Date().toISOString(),from,to,note:`Status schimbat din ${labels[from]} în ${labels[to]}`});touch(w);render();toast(`Lucrarea este ${labels[to].toLowerCase()}`)}
function manifest(w){const p=personFor(w);return{schemaVersion:"1.0",taskId:`task-${w.id}`,createdAt:new Date().toISOString(),person:p,work:{id:w.id,title:w.title,workType:w.workType,targetDirectory:w.targetDirectory},requestedSkills:[...new Set(w.deliverables.map(d=>skillMap[d.type]))],requestedDeliverables:w.deliverables.map(({type,label})=>({type,label})),initialStatus:w.status,blockers:[...w.blockers,...requiredMissing(w)]}}
function exportManifest(w){const blob=new Blob([JSON.stringify(manifest(w),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${w.id}-manifest.json`;a.click();URL.revokeObjectURL(a.href);toast("Manifest exportat")}
function toast(msg){$("toast").textContent=msg;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2200)}
function openDialog(){const box=$("deliverableChoices");box.innerHTML=deliverableTypes.map(d=>`<label><input type="checkbox" name="deliverables" value="${d.type}" checked>${d.label}</label>`).join("");$("formError").textContent="";$("workDialog").showModal()}
$("workForm").addEventListener("submit",e=>{if(e.submitter?.value==="cancel")return; e.preventDefault();const data=new FormData(e.currentTarget),fullName=data.get("fullName")?.trim(),birthDate=data.get("birthDate"),workType=data.get("workType"),targetDirectory=data.get("targetDirectory")?.trim(),chosen=data.getAll("deliverables");if(!fullName||!birthDate||!workType||!targetDirectory||!chosen.length){$("formError").textContent="Completează toate câmpurile și alege cel puțin un livrabil.";return}const id=crypto.randomUUID(),personId=`person-${id}`;state.persons.push({id:personId,fullName,birthDate});const now=new Date().toISOString(),w={id:`work-${id}`,personId,title:workType,workType,targetDirectory,status:"pregatita",deliverables:deliverableTypes.filter(d=>chosen.includes(d.type)).map((d,i)=>({...d,id:`${id}-${i}`,state:"pending"})),history:[{at:now,from:"date-validate",to:"pregatita",note:"Manifest pregătit în prototip"}],updatedAt:now,blockers:[]};state.works.unshift(w);selectedId=w.id;save();$("workDialog").close();e.currentTarget.reset();render();toast("Lucrare pregătită; manifestul poate fi exportat")});
function setTheme(theme){const selected=theme==="atlas-variant-2"?theme:"current";document.documentElement.dataset.theme=selected;document.querySelectorAll("[data-theme-option]").forEach(button=>{const active=button.dataset.themeOption===selected;button.classList.toggle("active",active);button.setAttribute("aria-pressed",String(active))});localStorage.setItem(THEME_STORAGE_KEY,selected)}
document.querySelectorAll("[data-theme-option]").forEach(button=>button.addEventListener("click",()=>setTheme(button.dataset.themeOption)));
setTheme(localStorage.getItem(THEME_STORAGE_KEY)||"current");
[$("searchInput"),$("statusFilter"),$("typeFilter")].forEach(el=>el.addEventListener("input",render));$("newWorkBtn").onclick=openDialog;render();
